/* Nedlloyd feature layer: themes, WhatsApp, quote form, AI chat + site search, tracking, brochure, back-to-top */
(function(){
  if (window.__nl) return; window.__nl = 1;
  var ROOT = (function(){ var s=document.currentScript&&document.currentScript.src||''; var m=s.match(/^(.*)\/addons\/nedlloyd\.js/); return m?m[1]:''; })();
  var SITE = ROOT + '/nedlloydgroup.com/';
  var WA = '919910694210', PHONE = '+91 11 4986 6666', EMAIL = 'info@nedlloydgroup.com';
  var BROCHURE = SITE + 'downloads/Nedlloyd-Company-Profile.pdf';
  var $ = function(h){ var d=document.createElement('div'); d.innerHTML=h.trim(); return d.firstChild; };
  var api = function(path, body){ return fetch(ROOT + '/api/' + path, body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}).then(function(r){ if(!r.ok) throw new Error(r.status); return r.json(); }); };
  var toast = function(t){ var e=document.getElementById('nl-toast'); e.textContent=t; e.style.display='block'; clearTimeout(e._t); e._t=setTimeout(function(){e.style.display='none';},2600); };

  /* ---------- prefs: language, text size, motion, contrast ---------- */
  var PREF={}; try{PREF=JSON.parse(localStorage.getItem('nl-pref')||'{}');}catch(e){}
  function savePref(){ try{localStorage.setItem('nl-pref',JSON.stringify(PREF));}catch(e){} applyPref(); }
  function applyPref(){ var r=document.documentElement; r.style.fontSize=PREF.big?'112%':''; r.classList.toggle('nl-reduce',!!PREF.reduce); r.classList.toggle('nl-contrast',!!PREF.contrast); r.setAttribute('lang',PREF.hi?'hi':'en'); }
  var HI={greet:'नमस्ते! मैं Nedlloyd सहायक हूँ। एयर, सी और लैंड फ्रेट, प्रोजेक्ट कार्गो, हमारे ऑफ़िस — या शिपमेंट ट्रैक करने के बारे में पूछें।',quote:'कोटेशन लें',ai:'Nedlloyd AI से पूछें',wa:'WhatsApp',chips:['आप कौन सी सेवाएँ देते हैं?','शिपमेंट कैसे ट्रैक करें?','आपके ऑफ़िस कहाँ हैं?','कोटेशन लें']};
  /* ---------- theme ---------- */
  var THEMES=['white','blue','dark'];
  function setTheme(t){ document.documentElement.setAttribute('data-nl-theme',t); try{localStorage.setItem('nl-theme',t);}catch(e){} document.querySelectorAll('#nl-dock [data-theme]').forEach(function(b){b.classList.toggle('on',b.dataset.theme===t);}); }
  var saved='white'; try{saved=localStorage.getItem('nl-theme')||'white';}catch(e){}

  /* ---------- dock (top) ---------- */
  var dock=$('<div id="nl-dock" class="nl-noinvert"><span class="lbl" style="opacity:.6;padding:0 6px">Theme</span>'+THEMES.map(function(t){return '<button data-theme="'+t+'">'+t[0].toUpperCase()+t.slice(1)+'</button>';}).join('')+
    '<span class="sep"></span><button data-pref="hi" title="हिन्दी / English">हि</button><button data-pref="big" title="Larger text">A+</button><button data-pref="reduce" title="Reduce motion">≈</button><button data-pref="contrast" title="High contrast">◐</button><span class="sep"></span>'+openNow()+'<button data-share title="Share this page">Share</button><a href="'+SITE+'dashboard.html" title="Client dashboard">Client Login</a><a class="brochure" href="'+BROCHURE+'" download>⬇ Company Profile</a></div>');
  dock.querySelectorAll('[data-theme]').forEach(function(b){ b.onclick=function(){ setTheme(b.dataset.theme); }; }); dock.querySelector('[data-share]').onclick=share; dock.querySelectorAll('[data-pref]').forEach(function(b){ b.onclick=function(){ PREF[b.dataset.pref]=!PREF[b.dataset.pref]; savePref(); b.classList.toggle('on',!!PREF[b.dataset.pref]); if(b.dataset.pref==='hi') applyLang(); }; if(PREF[b.dataset.pref]) b.classList.add('on'); });

  /* ---------- floating actions ---------- */
  var ICON_WA='<svg viewBox="0 0 24 24"><path d="M12 2a10 10 0 0 0-8.6 15.1L2 22l5-1.3A10 10 0 1 0 12 2zm0 18a8 8 0 0 1-4.1-1.1l-.3-.2-3 .8.8-2.9-.2-.3A8 8 0 1 1 12 20zm4.4-6c-.2-.1-1.4-.7-1.6-.8-.2-.1-.4-.1-.5.1l-.7.9c-.1.2-.3.2-.5.1a6.5 6.5 0 0 1-3.3-2.9c-.2-.4.3-.4.7-1.2.1-.2 0-.3 0-.4l-.7-1.7c-.2-.5-.4-.4-.5-.4h-.5a1 1 0 0 0-.7.3 3 3 0 0 0-.9 2.2 5.2 5.2 0 0 0 1.1 2.7 11.8 11.8 0 0 0 4.5 4 5 5 0 0 0 3 .7 2.6 2.6 0 0 0 1.7-1.2 2 2 0 0 0 .1-1.2c0-.1-.2-.2-.4-.3z"/></svg>';
  var ICON_AI='<svg viewBox="0 0 24 24"><path d="M12 3a9 9 0 0 0-9 9 8.9 8.9 0 0 0 1.5 5L3 21l4.2-1.3A9 9 0 1 0 12 3zm-3 10a1.3 1.3 0 1 1 0-2.6 1.3 1.3 0 0 1 0 2.6zm3 0a1.3 1.3 0 1 1 0-2.6 1.3 1.3 0 0 1 0 2.6zm3 0a1.3 1.3 0 1 1 0-2.6 1.3 1.3 0 0 1 0 2.6z"/></svg>';
  var ICON_Q='<svg viewBox="0 0 24 24"><path d="M3 5h18v2H3zm0 6h12v2H3zm0 6h18v2H3z"/></svg>';
  var fab=$('<div id="nl-fab" class="nl-noinvert"><button class="quote" id="nl-quote-btn">'+ICON_Q+'<span class="t">Get a Quote</span></button><button class="ai" id="nl-ai-btn">'+ICON_AI+'<span class="t">Ask Nedlloyd AI</span></button><a class="wa" target="_blank" rel="noopener" href="https://wa.me/'+WA+'?text='+encodeURIComponent('Hi Nedlloyd, I want to move cargo. ')+'">'+ICON_WA+'<span class="t">WhatsApp</span></a></div>');

  /* ---------- quote modal ---------- */
  var modal=$('<div id="nl-modal"><div class="card"><button class="x" aria-label="close">×</button><div class="body"></div></div></div>');
  var FORM='<h3>Get a Quote</h3><p class="sub">Tell us what\'s moving — we reply within one business day.</p><form id="nl-quote-form"><div class="grid">'+
   '<label>Your name*<input name="name" required></label><label>Company<input name="company"></label>'+
   '<label>Email*<input name="email" type="email" required></label><label>Phone / WhatsApp*<input name="phone" required></label>'+
   '<label class="full">Mode<div class="modes">'+['Air','Sea','Land','Project / Heavy Lift','Charter','Warehousing','Customs','4PL','Partner / Vendor','Callback'].map(function(m,i){return '<label><input type="radio" name="mode" value="'+m+'"'+(i==0?' checked':'')+'><span>'+m+'</span></label>';}).join('')+'</div></label>'+
   '<label>Origin<input name="origin" placeholder="City / port"></label><label>Destination<input name="destination" placeholder="City / site"></label>'+
   '<label>Cargo<input name="cargo" placeholder="e.g. 2 transformers, 48 t each"></label><label>Target date<input name="date" type="date"></label>'+
   '<label class="full">Message<textarea name="message" rows="3"></textarea></label></div>'+
   '<button class="btn" type="submit">Send request →</button><p class="sub" style="margin-top:10px;font-size:12px">Or call '+PHONE+' · <a href="mailto:'+EMAIL+'">'+EMAIL+'</a></p></form>';
  function openQuote(pre){ modal.querySelector('.body').innerHTML=FORM; modal.classList.add('open');
    var f=modal.querySelector('#nl-quote-form'); if(pre) Object.keys(pre).forEach(function(k){ var el=f.elements[k]; if(el) el.value=pre[k]; });
    f.onsubmit=function(e){ e.preventDefault(); var d={}; new FormData(f).forEach(function(v,k){d[k]=v;}); d.page=location.pathname; d.utm=UTM;
      api('leads',d).then(function(r){ modal.querySelector('.body').innerHTML='<div class="ok"><b>Request received ✓</b>Reference '+(r.ref||'')+'. We\'ll reply by <b>'+replyBy()+'</b>.<br><br><a href="https://wa.me/'+WA+'?text='+encodeURIComponent('Hi, I just sent quote request '+(r.ref||'')+' on your website.')+'" target="_blank" style="color:#25D366;font-weight:700">Continue on WhatsApp →</a></div>'; })
      .catch(function(){ var body='Quote request%0A'+Object.keys(d).map(function(k){return k+': '+d[k];}).join('%0A'); location.href='mailto:'+EMAIL+'?subject=Quote request&body='+body; }); }; }
  modal.querySelector('.x').onclick=function(){modal.classList.remove('open');}; modal.onclick=function(e){ if(e.target===modal) modal.classList.remove('open'); };

  /* ---------- AI chat + search + tracking ---------- */
  var chat=$('<div id="nl-chat" class="nl-noinvert"><header><div><b>Nedlloyd Assistant</b><small>AI · answers, site search, shipment tracking</small></div><span style="display:flex;gap:2px"><button data-voice title="Speak your question">🎤</button><button data-speak title="Read answers aloud">🔊</button><button data-mail title="Email this chat">✉</button><button data-clear title="Clear chat">🗑</button><button aria-label="close">×</button></span></header>'+
    '<div class="tabs"><button class="on" data-tab="chat">Ask AI</button><button data-tab="search">Search</button><button data-tab="track">Track</button><button data-tab="links">Quick links</button></div>'+
    '<div class="log"></div><div class="chips"></div><form><input placeholder="Ask about air, sea, land, project cargo…" autocomplete="off"><button>Send</button></form></div>');
  var log=chat.querySelector('.log'), chips=chat.querySelector('.chips'), form=chat.querySelector('form'), inp=chat.querySelector('input'), tab='chat';
  function msg(t,who){ var m=$('<div class="m '+who+'"></div>'); if(who==='a') m.innerHTML=t; else m.textContent=t; log.appendChild(m); log.scrollTop=log.scrollHeight; return m; }
  var LINKS=[['Get a Quote','quote'],['Track a shipment',SITE+'track.html'],['Client Dashboard',SITE+'dashboard.html'],['Services',SITE+'services.html'],['Air · Sea · Land',SITE+'services.html'],['Industries',SITE+'industries.html'],['Case Studies',SITE+'case-studies.html'],['FAQ (100)',SITE+'faq.html'],['Offices & Warehouses',SITE+'offices.html'],['Compliances',SITE+'compliances.html'],['Careers',SITE+'careers.html'],['Contact',SITE+'contact.html'],['Freight Tools (CBM · transit · checklists)',SITE+'tools.html'],['Glossary',SITE+'glossary.html'],['Incoterms',SITE+'incoterms.html'],['Container sizes',SITE+'containers.html'],['Company Profile PDF',BROCHURE],['WhatsApp us','https://wa.me/'+WA]];
  var CHIPS={links:[],chat:['What services do you offer?','Which service do I need?','Quick quote','How do I track my shipment?','Where are your offices?'],
             search:['warehousing','customs','project cargo','oil & gas','careers','compliances'],
             track:['NL-2026-0001','NL-2026-0002','NL-2026-0003']};
  var PH={links:'Type a page name…',chat:'Ask about air, sea, land, project cargo…',search:'Search pages, services, industries…',track:'Enter Job Number, e.g. NL-2026-0001'};
  function setTab(t){ tab=t; chat.querySelectorAll('.tabs button').forEach(function(b){b.classList.toggle('on',b.dataset.tab===t);}); inp.placeholder=PH[t];
    chips.innerHTML=''; if(t==='links'){ log.innerHTML=''; var rv=[]; try{ rv=JSON.parse(localStorage.getItem('nl-recent')||'[]'); }catch(e){} if(rv.length){ var r=msg('','a'); r.innerHTML='<b style="font-size:12px;color:#666">Recently viewed</b><br>'+rv.slice(0,5).map(function(p){return '<a class="res" href="'+p.u+'"><b>'+p.t+'</b></a>';}).join(''); } var m=msg('','a'); m.innerHTML=LINKS.map(function(l){return '<a class="res" href="'+(l[1]==='quote'?'#':l[1])+'" data-q="'+(l[1]==='quote'?'1':'')+'"><b>'+l[0]+'</b></a>';}).join('<div style="height:6px"></div>'); m.querySelectorAll('[data-q="1"]').forEach(function(a){a.onclick=function(e){e.preventDefault();openQuote();};}); }
    CHIPS[t].forEach(function(c){ var b=$('<button>'+c+'</button>'); b.onclick=function(){ inp.value=c; form.requestSubmit?form.requestSubmit():form.dispatchEvent(new Event('submit',{cancelable:true})); }; chips.appendChild(b); }); }
  chat.querySelectorAll('.tabs button').forEach(function(b){ b.onclick=function(){ setTab(b.dataset.tab); }; });
  chat.querySelector('header [aria-label=close]').onclick=function(){ chat.classList.remove('open'); }; chat.querySelector('[data-voice]').onclick=voice; chat.querySelector('[data-speak]').onclick=function(){ PREF.speak=!PREF.speak; savePref(); toast(PREF.speak?'Read-aloud on':'Read-aloud off'); }; chat.querySelector('[data-mail]').onclick=emailTranscript; chat.querySelector('[data-clear]').onclick=function(){ hist=[]; saveHist(); log.innerHTML=''; setTab('chat'); };
  var hist=[]; try{ hist=JSON.parse(sessionStorage.getItem('nl-hist')||'[]'); }catch(e){} var idx=null;
  function saveHist(){ try{ sessionStorage.setItem('nl-hist',JSON.stringify(hist.slice(-20))); }catch(e){} }
  function applyLang(){ var hi=!!PREF.hi; document.querySelectorAll('#nl-fab .t').forEach(function(t,i){ t.textContent=hi?[HI.quote,HI.ai,HI.wa][i]:['Get a Quote','Ask Nedlloyd AI','WhatsApp'][i]; }); CHIPS.chat=hi?HI.chips:['What services do you offer?','How do I track my shipment?','Where are your offices?','Do you handle over-dimensional cargo?','Get a quote']; if(tab==='chat') setTab('chat'); }
  var rec=null; function voice(){ var SR=window.SpeechRecognition||window.webkitSpeechRecognition; if(!SR){ toast('Voice input not supported in this browser'); return; } if(rec){ rec.stop(); rec=null; return; } rec=new SR(); rec.lang=PREF.hi?'hi-IN':'en-IN'; rec.onresult=function(e){ inp.value=e.results[0][0].transcript; form.requestSubmit?form.requestSubmit():form.dispatchEvent(new Event('submit',{cancelable:true})); }; rec.onend=function(){ rec=null; }; rec.start(); toast('Listening…'); }
  function speak(t){ if(!window.speechSynthesis) return; var u=new SpeechSynthesisUtterance(t.replace(/<[^>]+>/g,'')); u.lang=PREF.hi?'hi-IN':'en-IN'; speechSynthesis.cancel(); speechSynthesis.speak(u); }
  function emailTranscript(){ var body=hist.map(function(m){return (m.role==='user'?'You: ':'Nedlloyd: ')+m.content;}).join('%0A%0A'); location.href='mailto:?subject=My chat with Nedlloyd&body='+body; }
  var WIZ=null; var WQ=[['What are you moving?',['Heavy / over-dimensional equipment','Standard palletised or boxed cargo','Documents, samples or small parcels','Full plant / multi-vendor programme']],['How urgent is it?',['Next 72 hours','Within 2 weeks','Flexible / best cost']],['Where is it going?',['Within India','India ↔ USA / Canada','India ↔ Gulf / Middle East','India ↔ Europe / Asia / Africa']]];
  function say(t){ var m=msg(t,'a'); hist.push({role:'assistant',content:t.replace(/<[^>]+>/g,'')}); saveHist(); return m; }
  function wizard(step,ans){ if(step===0) WIZ=[]; if(ans) WIZ.push(ans); if(step<WQ.length){ var m=say(WQ[step][0]); var c=$('<div class="chips" style="border:0;padding:6px 0"></div>'); WQ[step][1].forEach(function(o){ var b=$('<button>'+o+'</button>'); b.onclick=function(){ msg(o,'u'); wizard(step+1,o); }; c.appendChild(b); }); m.appendChild(c); return; }
    var a=WIZ; var svc = a[0].indexOf('Heavy')===0?'Project Cargo & Heavy Lift': a[0].indexOf('Documents')===0?'Express Courier & Cargo': a[0].indexOf('Full plant')===0?'4PL Solutions': (a[1].indexOf('72')===0?'Air Freight (or charter)':(a[2]==='Within India'?'Land Transport (Road & Rail)':'Sea Freight'));
    say('<b>Recommended: '+svc+'</b><br>'+(a[1].indexOf('72')===0?'For a 72-hour deadline we plan air or charter first. ':'')+'Next step: <a href="'+SITE+'services.html">see the service</a> or start a quick quote below.','a'); quickQuote(0); }
  var QQ=null; var QQF=[['origin','Where does the cargo start? (city / port)'],['destination','Where should it be delivered?'],['cargo','What is the cargo? (pieces, weight, dimensions)'],['date','Target date?'],['name','Your name?'],['phone','Phone / WhatsApp number?'],['email','Email for the quote?']];
  function quickQuote(i,val){ if(i===0){ QQ={mode:'Chat quick quote',page:location.pathname,utm:UTM}; say('Quick quote — 7 short questions. Type <b>cancel</b> to stop.'); } else if(val!==undefined) QQ[QQF[i-1][0]]=val; if(i<QQF.length){ say(QQF[i][1]); QQ._i=i; return; } var d=QQ; QQ=null; var w=msg('Sending…','a'); api('leads',d).then(function(r){ w.innerHTML='<b>Request '+r.ref+' received ✓</b> We reply within one business day. <a href="https://wa.me/'+WA+'?text='+encodeURIComponent('Hi, I sent quick quote '+r.ref)+'" target="_blank">Continue on WhatsApp →</a>'; }).catch(function(){ w.innerHTML='Could not send — please use the Get a Quote button.'; }); }
  function loadIdx(){ return idx?Promise.resolve(idx):fetch(ROOT+'/addons/search-index.json').then(function(r){return r.json();}).then(function(j){idx=j;return j;}); }
  function localSearch(q){ q=q.toLowerCase(); var terms=q.split(/\s+/).filter(Boolean); return loadIdx().then(function(j){ return j.map(function(p){ var t=(p.title+' '+p.text).toLowerCase(); var s=terms.reduce(function(a,w){return a+(t.split(w).length-1)*(p.title.toLowerCase().indexOf(w)>=0?5:1);},0); return [s,p]; }).filter(function(x){return x[0]>0;}).sort(function(a,b){return b[0]-a[0];}).slice(0,6).map(function(x){return x[1];}); }); }
  var FAQD=null; fetch(ROOT+'/addons/faq.json').then(function(r){return r.json();}).then(function(j){FAQD=j;}).catch(function(){});
  function faqAnswer(q){ if(!FAQD) return null; var t=q.toLowerCase().split(/\W+/).filter(function(w){return w.length>2;}); var best=null,bs=0; FAQD.forEach(function(f){ var ql=f.q.toLowerCase(); var sc=t.reduce(function(a,w){return a+(ql.indexOf(w)>=0?2:(f.a.toLowerCase().indexOf(w)>=0?1:0));},0); if(sc>bs){bs=sc;best=f;} }); return (best&&bs>=3)?'<b>'+best.q+'</b><br>'+best.a+' <a href="'+SITE+'faq.html#faq-'+best.id+'">FAQ →</a>':null; }
  function offlineAnswer(q){ var fa=faqAnswer(q); if(fa) return fa; var s=q.toLowerCase();
    if(/track|status|where is my/.test(s)) return 'Use the <b>Track shipment</b> tab with your Job Number, or open the <a href="'+SITE+'tracking.html">Customer Dashboard</a>. Every job runs through 10 milestones — Booking Confirmed → Job Closed.';
    if(/quote|price|rate|cost/.test(s)) return 'Happy to help. Tap <b>Get a Quote</b> (bottom right) or WhatsApp us at +91 99106 94210 with origin, destination, cargo (weight/dimensions) and target date.';
    if(/office|where|address|contact|phone|email/.test(s)) return 'Head office: T-95A, 4th Floor, C.L. House, Yusuf Sarai Commercial Centre, New Delhi-110049 · +91 11 4986 6666 · info@nedlloydgroup.com. Also Mumbai, Bangalore, Kolkata; Austin, Miami, Cleveland (USA); Mississauga (Canada). <a href="'+SITE+'contact.html">All locations →</a>';
    if(/air/.test(s)) return 'Air freight: express, priority and deferred options through globally reliable airlines, with AWB and customs milestones tracked on your dashboard. <a href="'+SITE+'services.html">Services →</a>';
    if(/sea|ocean|ship|container/.test(s)) return 'Sea freight: FCL, LCL, breakbulk and RO/RO — plus project and out-of-gauge cargo on breakbulk and heavy-lift vessels. <a href="'+SITE+'services.html">Services →</a>';
    if(/road|rail|land|truck|trailer/.test(s)) return 'Land transport: road and rail across India\'s industrial corridors, ports and inland hubs — heavy-haul and over-dimensional included, every leg tracked. <a href="'+SITE+'services.html">Services →</a>';
    if(/project|heavy|odc|over.?dimension|oversize/.test(s)) return 'Project cargo is our core work: route surveys, permits and escorts, engineered load plans, hydraulic axles and cranes, customs project registration and on-site supervision. <a href="'+SITE+'industries.html">Industries we serve →</a>';
    if(/warehouse|storage|bonded/.test(s)) return '20+ IT-enabled warehouses across India — general, custom-bonded, temperature-controlled and project warehousing with real-time inventory visibility.';
    if(/customs|clearance|broker/.test(s)) return 'Customs brokerage: import/export documentation, advice on commodity, duties and restrictions, payment of duties and bonds — shipping bills and BOE/DO attached to each milestone.';
    if(/service|what do you/.test(s)) return 'We offer Air, Sea and Land freight, Customs Brokerage, Warehousing & Distribution (20+ sites), Project Cargo & Heavy Lift, Charter, 4PL, Express Courier, E-commerce Fulfilment, Reverse Logistics and Cargo Insurance. <a href="'+SITE+'services.html">See all →</a>';
    if(/industr|sector|oil|power|steel|rail|auto|defence|solar|wind/.test(s)) return 'We move for Oil & Gas, Power, BESS, Solar, Wind, EPC & Infrastructure, Steel & Cement, Automotive, Rail and Defence. <a href="'+SITE+'industries.html">Industries →</a>';
    if(/career|job|hiring|work/.test(s)) return 'We\'re growing across India and abroad. <a href="'+SITE+'careers.html">Open roles →</a>';
    if(/iso|certif|complian|wca/.test(s)) return 'Certified ISO 9001:2015, ISO 14001, OHSAS 18001; WCA Network partner. <a href="'+SITE+'compliances.html">Compliances →</a>';
    return 'I can help with services, industries, offices, tracking and quotes. Try: "Do you handle over-dimensional cargo?" — or tap <b>Get a Quote</b>.'; }
  function trackRender(j){ var names=['Booking Confirmed','Cargo Picked Up','Customs (Origin)','Departed','In Transit','Arrived Destination','Customs (Dest.)','Out for Delivery','Delivered (POD)','Job Closed'];
    var h='<b>'+j.job+'</b> · '+j.client+'<br>'+j.origin+' → '+j.destination+' · '+j.mode+' · '+j.cargo+'<div class="ms" style="margin-top:8px">'+names.map(function(n,i){ var k=i+1; return '<i class="'+(k<j.stage?'done':k===j.stage?'cur':'')+'">'+k+'</i><span>'+n+(j.dates&&j.dates[i]?' · '+j.dates[i]:'')+'</span>'; }).join('')+'</div>'; return h; }
  form.onsubmit=function(e){ e.preventDefault(); var q=inp.value.trim(); if(!q) return; inp.value=''; msg(q,'u'); if(tab==='chat'){ hist.push({role:'user',content:q}); saveHist(); }
    if(tab==='search'){ localSearch(q).then(function(r){ if(!r.length) return msg('No pages matched. Try another word, or ask the AI tab.','a'); var m=msg('','a'); m.innerHTML=r.map(function(p){return '<a class="res" href="'+SITE+p.url+'"><b>'+p.title+'</b><span>'+p.snippet+'</span></a>';}).join('<div style="height:6px"></div>'); }); return; }
    if(tab==='track'){ var w=msg('Looking up '+q+'…','a'); api('track/'+encodeURIComponent(q)).then(function(j){ w.innerHTML=trackRender(j); }).catch(function(){ w.innerHTML='No job found for <b>'+q+'</b>. Check the Job Number on your Booking Note, or <a href="'+SITE+'dashboard.html">sign in to the dashboard</a>.'; }); return; }
    if(QQ){ if(/^cancel$/i.test(q)){ QQ=null; msg('Cancelled.','a'); return; } quickQuote(QQ._i+1,q); return; }
    if(/^(get a quote|कोटेशन लें)$/i.test(q)){ msg('Opening the quote form…','a'); openQuote(); return; }
    if(/which service do i need|service wizard|help me choose/i.test(q)){ wizard(0); return; }
    if(/^quick quote$/i.test(q)){ quickQuote(0); return; }
    var w=msg('…','a');
    api('chat',{messages:hist.slice(-10),page:location.pathname,lang:PREF.hi?'hi':'en'}).then(function(r){ w.innerHTML=r.html||r.text; hist.push({role:'assistant',content:r.text||''}); saveHist(); if(PREF.speak) speak(r.text||''); })
      .catch(function(){ var a=offlineAnswer(q); w.innerHTML=a; hist.push({role:'assistant',content:a.replace(/<[^>]+>/g,'')}); saveHist(); if(PREF.speak) speak(a); }); };

  /* ---------- back to top + toast ---------- */
  var top=$('<button id="nl-top" class="nl-noinvert" aria-label="Back to top">↑</button>'); top.onclick=function(){ window.scrollTo({top:0,behavior:'smooth'}); };
  window.addEventListener('scroll',function(){ top.classList.toggle('show',window.scrollY>900); },{passive:true});

  function replyBy(){ var d=new Date(Date.now()+(330+new Date().getTimezoneOffset())*60000); var add=(d.getDay()===6)?2:(d.getDay()===0?1:(d.getHours()>=18?1:0)); if(d.getDay()===5&&d.getHours()>=18) add=2; d.setDate(d.getDate()+add); return d.toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'short'}); }
  function pageExtras(){
    var rt=document.querySelector('.policy-main-content-text:not(.nl-init)'); if(rt){ rt.classList.add('nl-init'); var words=rt.innerText.split(/\s+/).length; var hs=rt.querySelectorAll('h2'); var bar=$('<div style="display:flex;flex-wrap:wrap;gap:8px 16px;align-items:center;font-size:.85em;opacity:.75;margin-bottom:1.5em"><a href="'+SITE+'" style="color:inherit">Home</a><span>›</span><span>'+document.title.split('—')[0].trim()+'</span><span style="margin-left:auto">'+Math.max(1,Math.round(words/200))+' min read</span></div>'); rt.parentNode.insertBefore(bar,rt);
      if(hs.length>=4){ var toc=$('<div style="margin:0 0 2em;padding:1em 1.2em;border:1px solid var(--_color---border--main);border-radius:12px;font-size:.9em"><b>On this page</b><div style="display:flex;flex-wrap:wrap;gap:6px 14px;margin-top:6px"></div></div>'); hs.forEach(function(h,i){ if(!h.id) h.id='sec-'+i; var a=$('<a href="#'+h.id+'" style="color:inherit">'+h.textContent+'</a>'); toc.lastChild.appendChild(a); }); rt.parentNode.insertBefore(toc,rt); }
      var fb=$('<div style="margin-top:3em;padding-top:1.5em;border-top:1px solid var(--_color---border--main);font-size:.9em"><b>Was this page helpful?</b> <button data-v="up" style="margin-left:8px;padding:6px 12px;border:1px solid var(--_color---border--main);border-radius:999px;background:transparent;color:inherit;cursor:pointer">👍 Yes</button> <button data-v="down" style="padding:6px 12px;border:1px solid var(--_color---border--main);border-radius:999px;background:transparent;color:inherit;cursor:pointer">👎 No</button></div>'); fb.querySelectorAll('button').forEach(function(b){ b.onclick=function(){ api('feedback',{page:location.pathname,vote:b.dataset.v}).catch(function(){}); fb.innerHTML='<b>Thanks for the feedback.</b>'+(b.dataset.v==='down'?' Tell us what was missing: <a href="#" onclick="NL.openChat();return false">ask the assistant</a>.':''); }; }); rt.parentNode.appendChild(fb); }
    document.querySelectorAll('[data-nl-faq]:not(.nl-vote)').forEach(function(d){ d.classList.add('nl-vote'); var p=d.querySelector('p'); if(!p) return; var v=$('<span style="font-size:.8em;opacity:.7;margin-left:8px">Helpful? <a href="#" data-v="up">👍</a> <a href="#" data-v="down">👎</a></span>'); v.querySelectorAll('a').forEach(function(a){ a.onclick=function(e){ e.preventDefault(); api('feedback',{page:location.pathname,item:d.id,vote:a.dataset.v}).catch(function(){}); v.textContent=' Thanks!'; }; }); p.appendChild(v); });
    var to=document.querySelector('[data-nl-track-out] .ms:not(.nl-share)'); if(to){ to.classList.add('nl-share'); var b=$('<button style="padding:8px 12px;border:0;border-radius:8px;background:#25D366;color:#fff;cursor:pointer;margin:8px 0">Share status on WhatsApp</button>'); b.onclick=function(){ window.open('https://wa.me/?text='+encodeURIComponent(to.innerText.split('\n')[0]+' — '+location.origin+location.pathname+'?job='+encodeURIComponent(document.querySelector('[data-nl-track-input]').value)),'_blank'); }; to.parentNode.insertBefore(b,to); }
  }
  window.addEventListener('offline',function(){ toast('You are offline — forms will fall back to email.'); }); window.addEventListener('online',function(){ toast('Back online'); });
  /* ---------- page enhancers (FAQ search, public track, tel links, UTM, careers apply, newsletter) ---------- */
  function enhance(){
    var fi=document.querySelector('[data-nl-faq-search]:not(.nl-init)'); if(fi){ fi.classList.add('nl-init'); fi.oninput=function(){ var q=fi.value.toLowerCase(); var any=false; document.querySelectorAll('[data-nl-faq]').forEach(function(d){ var ok=!q||d.textContent.toLowerCase().indexOf(q)>=0; d.style.display=ok?'':'none'; if(ok) any=true; if(q&&ok) d.open=true; }); document.querySelectorAll('[data-nl-faq-cat]').forEach(function(c){ var n=c.nextElementSibling, vis=false; while(n&&n.tagName==='DETAILS'){ if(n.style.display!=='none') vis=true; n=n.nextElementSibling; } c.style.display=vis?'':'none'; }); var e=document.querySelector('[data-nl-faq-empty]'); if(e) e.style.display=any?'none':''; }; if(location.hash){ var d=document.querySelector(location.hash); if(d&&d.tagName==='DETAILS'){ d.open=true; d.scrollIntoView(); } } }
    var tb=document.querySelector('[data-nl-track-btn]:not(.nl-init)'); if(tb){ tb.classList.add('nl-init'); var ti=document.querySelector('[data-nl-track-input]'), to=document.querySelector('[data-nl-track-out]'); var go=function(){ var v=ti.value.trim(); if(!v) return; to.innerHTML='<p>Looking up '+v+'…</p>'; api('track/'+encodeURIComponent(v)).then(function(j){ to.innerHTML='<p><button onclick="navigator.clipboard.writeText(location.origin+location.pathname+\'?job='+j.job+'\');window.NL&&NL.toast(\'Tracking link copied\')" style="padding:8px 12px;border:1px solid #ccc;border-radius:8px;background:transparent;color:inherit;cursor:pointer">Copy tracking link</button> <button onclick="window.print()" style="padding:8px 12px;border:1px solid #ccc;border-radius:8px;background:transparent;color:inherit;cursor:pointer">Print</button></p><div class="ms" style="display:grid;grid-template-columns:28px 1fr;gap:8px 12px;margin:12px 0"><b style="grid-column:1/-1">'+j.job+' · '+j.client+' · '+j.origin+' → '+j.destination+' · '+j.mode+' · '+j.cargo+'</b>'+j.milestones.map(function(n,i){var k=i+1;return '<i style="width:26px;height:26px;border-radius:50%;display:inline-flex;align-items:center;justify-content:center;font-style:normal;font-weight:700;font-size:12px;background:'+(k<j.stage?'#111;color:#fff':k===j.stage?'#FF6A00;color:#fff':'#ddd')+'">'+k+'</i><span>'+n+(j.dates[i]?' · '+j.dates[i]:'')+(j.docs[i]?' <small style="opacity:.6">('+j.docs[i]+')</small>':'')+'</span>';}).join('')+'</div>'; }).catch(function(){ to.innerHTML='<p>No job found for <b>'+v+'</b>. Check the Job Number on your Booking Note or contact us.</p>'; }); }; tb.onclick=go; ti.onkeydown=function(e){ if(e.key==='Enter') go(); }; var m=location.search.match(/job=([^&]+)/); if(m){ ti.value=decodeURIComponent(m[1]); go(); } }
    document.querySelectorAll('.footer-link, .contact-info-item, p, div').forEach(function(el){ if(el.children.length||el.classList.contains('nl-init')) return; var t=el.textContent.trim(); if(/^\+?[0-9][0-9 ()\-]{8,}$/.test(t)&&!el.closest('a')){ el.classList.add('nl-init'); var a=document.createElement('a'); a.href='tel:'+t.replace(/[^0-9+]/g,''); a.textContent=t; a.style.color='inherit'; a.style.textDecoration='none'; el.textContent=''; el.appendChild(a); } });
    var cf=document.querySelector('.career-job-form, form[data-name*="Job" i], form[id*="apply" i]'); if(cf&&!cf.classList.contains('nl-init')){ cf.classList.add('nl-init'); cf.addEventListener('submit',function(e){ e.preventDefault(); e.stopPropagation(); var d={}; new FormData(cf).forEach(function(v,k){ if(typeof v==='string') d[k]=v; }); d.page=location.pathname; d.type='career'; api('leads',d).then(function(r){ toast('Application received · '+r.ref); cf.reset(); }).catch(function(){ toast('Could not send — email info@nedlloydgroup.com'); }); },true); }
  }
  /* tools */
  function tools(){
    var c=document.querySelector('[data-nl-tool=cbm]:not(.nl-init)'); if(c){ c.classList.add('nl-init'); var f=function(){ var l=+c.querySelector('[data-l]').value,w=+c.querySelector('[data-w]').value,h=+c.querySelector('[data-h]').value,n=+c.querySelector('[data-n]').value||1,kg=+c.querySelector('[data-kg]').value||0; if(!(l&&w&&h)) return; var cbm=l*w*h*n/1e6, vol=l*w*h*n/6000; c.querySelector('[data-out]').innerHTML='<strong>'+cbm.toFixed(3)+' CBM</strong> · air volumetric '+vol.toFixed(1)+' kg · chargeable '+Math.max(vol,kg).toFixed(1)+' kg · sea W/M '+Math.max(cbm,kg/1000).toFixed(3)+' t'; }; c.querySelectorAll('input').forEach(function(i){i.oninput=f;}); }
    var t=document.querySelector('[data-nl-tool=transit]:not(.nl-init)'); if(t){ t.classList.add('nl-init'); var T={'India → USA':{Air:'5–8 days door-to-door',Sea:'28–40 days (via East/West coast)',Land:'—'},'India → Canada':{Air:'5–8 days',Sea:'30–42 days',Land:'—'},'India → UAE / Gulf':{Air:'2–4 days',Sea:'6–12 days',Land:'—'},'India → Europe':{Air:'4–7 days',Sea:'18–28 days',Land:'—'},'India → China / East Asia':{Air:'3–6 days',Sea:'12–20 days',Land:'—'},'India → Africa':{Air:'4–8 days',Sea:'20–35 days',Land:'—'},'Domestic — metro to metro':{Air:'1–2 days',Sea:'—',Land:'2–5 days'},'Domestic — ODC convoy':{Air:'—',Sea:'—',Land:'planned per route survey (typically 7–30 days)'}}; var g=function(){ var l=t.querySelector('[data-lane]').value,m=t.querySelector('[data-mode]').value; t.querySelector('[data-out]').innerHTML='<strong>'+l+' by '+m+': '+(T[l][m]||'—')+'</strong> · includes customs on compliant docs; project cargo quoted individually.'; }; t.querySelectorAll('select').forEach(function(s){s.onchange=g;}); g(); }
    var d=document.querySelector('[data-nl-tool=docs]:not(.nl-init)'); if(d){ d.classList.add('nl-init'); var D={'Import into India':['Commercial invoice','Packing list','Bill of Lading / AWB','IEC certificate','Purchase order','Certificate of origin (if preferential duty)','BIS / other product approvals (if applicable)','Insurance certificate','GST registration','KYC of importer'],'Export from India':['Commercial invoice','Packing list','Shipping Bill (filed by Nedlloyd)','IEC certificate','Purchase order / LC','Certificate of origin','Export licence (if restricted)','ARE-1 / LUT (if applicable)','Insurance certificate'],'Project / ODC movement':['Cargo drawings with dimensions & weight','Centre of gravity / lifting points','Packing list per piece','Route survey report','State permits & NOCs','Police / NHAI escort approvals','Crane & axle plan','Project registration with Customs (imports)','Site access & unloading plan'],'Dangerous goods':['DG declaration (IMDG / IATA)','MSDS / SDS','UN number & packing group','DG packing certificate','Emergency contact','Segregation plan'],'Domestic road movement':['Invoice','E-way bill','Delivery challan','LR / consignment note (issued by Nedlloyd)','Insurance (if arranged)','Site delivery contact']}; var r=function(){ var k=d.querySelector('[data-type]').value; d.querySelector('[data-out]').innerHTML='<ul>'+D[k].map(function(x){return '<li>'+x+'</li>';}).join('')+'</ul>'; }; d.querySelector('[data-type]').onchange=r; r(); d.querySelector('[data-copy]').onclick=function(){ var k=d.querySelector('[data-type]').value; navigator.clipboard&&navigator.clipboard.writeText(k+':\n- '+D[k].join('\n- ')); toast('Checklist copied'); }; }
  }
  /* cookie notice */
  function cookieBar(){ try{ if(localStorage.getItem('nl-cookie')) return; }catch(e){} var b=$('<div id="nl-cookie" class="nl-noinvert" style="position:fixed;left:50%;bottom:70px;transform:translateX(-50%);z-index:9004;background:#111;color:#fff;padding:12px 16px;border-radius:14px;font:13px var(--nl-font);max-width:calc(100vw - 32px);width:520px;display:flex;gap:12px;align-items:center;box-shadow:0 10px 30px rgba(0,0,0,.3)"><span>We use essential cookies and anonymous visit counts only. See our <a href="'+SITE+'privacy-policy.html" style="color:#FF6A00">Privacy Policy</a>.</span><button style="background:#fff;color:#111;border:0;border-radius:999px;padding:8px 14px;font:600 12px var(--nl-font);cursor:pointer">OK</button></div>'); b.querySelector('button').onclick=function(){ try{localStorage.setItem('nl-cookie','1');}catch(e){} b.remove(); }; document.body.appendChild(b); }
  /* scroll progress + open-now + share + shortcuts */
  var prog=$('<div id="nl-prog" class="nl-noinvert" style="position:fixed;top:0;left:0;height:3px;background:#FF6A00;width:0;z-index:9005;pointer-events:none"></div>');
  window.addEventListener('scroll',function(){ var h=document.documentElement.scrollHeight-innerHeight; prog.style.width=(h>0?Math.min(100,scrollY/h*100):0)+'%'; },{passive:true});
  function openNow(){ var ist=new Date(Date.now()+(330+new Date().getTimezoneOffset())*60000); var d=ist.getDay(),hh=ist.getHours(); var open=d>=1&&d<=6&&hh>=9&&hh<18; return '<span class="lbl" title="Head office hours Mon–Sat 9–6 IST" style="padding:0 8px;opacity:.85"><span style="display:inline-block;width:7px;height:7px;border-radius:50%;background:'+(open?'#25D366':'#f5a623')+';margin-right:5px"></span>'+(open?'Open now':'Opens 9AM IST')+'</span>'; }
  function share(){ var u=location.href,t=document.title; if(navigator.share){ navigator.share({title:t,url:u}).catch(function(){}); return; } window.open('https://wa.me/?text='+encodeURIComponent(t+' '+u),'_blank'); }
  document.addEventListener('keydown',function(e){ if(e.target.matches('input,textarea,select')||e.metaKey||e.ctrlKey) return; if(e.key==='/'){ e.preventDefault(); chat.classList.add('open'); setTab('search'); inp.focus(); } if(e.key==='?'){ chat.classList.add('open'); setTab('chat'); inp.focus(); } if(e.key==='q'||e.key==='Q'){ openQuote(); } if(e.key==='Escape'){ chat.classList.remove('open'); modal.classList.remove('open'); } });
  var UTM={}; try{ location.search.replace(/[?&](utm_[a-z]+|ref|gclid|fbclid)=([^&]*)/g,function(_,k,v){UTM[k]=decodeURIComponent(v);}); if(Object.keys(UTM).length) sessionStorage.setItem('nl-utm',JSON.stringify(UTM)); UTM=JSON.parse(sessionStorage.getItem('nl-utm')||'{}'); }catch(e){}

  /* ---------- mount ---------- */
  function mount(){ if(!document.getElementById('nl-style')){ var st=document.createElement('style'); st.id='nl-style'; document.body.appendChild(st); fetch(ROOT+'/addons/nedlloyd.css').then(function(r){return r.text();}).then(function(t){ st.textContent=t; }); }
    new MutationObserver(function(){ if(!document.getElementById('nl-style')||!document.getElementById('nl-dock')) { setTimeout(mount,50); } }).observe(document.body,{childList:true});
    document.body.appendChild(dock); document.body.appendChild(fab); document.body.appendChild(chat); document.body.appendChild(modal); document.body.appendChild(top); document.body.appendChild(prog); document.body.appendChild($('<div id="nl-toast"></div>')); cookieBar();
    setTheme(saved); applyPref(); setTab('chat'); try{ var rv=JSON.parse(localStorage.getItem('nl-recent')||'[]').filter(function(p){return p.u!==location.pathname;}); rv.unshift({u:location.pathname,t:document.title.split('—')[0].trim()}); localStorage.setItem('nl-recent',JSON.stringify(rv.slice(0,8))); }catch(e){} if(hist.length){ hist.forEach(function(m){ msg(m.content,m.role==='user'?'u':'a'); }); } else msg(PREF.hi?HI.greet:'Hi! I\'m the Nedlloyd assistant. Ask me about air, sea and land freight, project cargo, our offices — or track a shipment.','a'); applyLang();
    document.getElementById('nl-quote-btn').onclick=function(){ openQuote(); };
    document.getElementById('nl-ai-btn').onclick=function(){ chat.classList.toggle('open'); if(chat.classList.contains('open')) inp.focus(); };
    document.addEventListener('click',function(e){ var a=e.target.closest&&e.target.closest('a'); if(!a) return; var t=(a.textContent||'').trim().toLowerCase(); var h=a.getAttribute('href')||'';
      if(/^(get a quote|talk with us|work with us|email us|speak to our team)$/.test(t) && !/mailto|dashboard|contact/.test(h)){ e.preventDefault(); e.stopPropagation(); openQuote(); } }, true);
    api('hit',{page:location.pathname,ref:document.referrer}).catch(function(){}); enhance(); tools(); pageExtras(); setInterval(function(){enhance();tools();pageExtras();},800); }
  if(document.body) mount(); else document.addEventListener('DOMContentLoaded',mount);
  window.NL={openQuote:openQuote,setTheme:setTheme,toast:toast,openChat:function(){chat.classList.add('open');}};
})();
